<?php
/**
 * Plugin Name: Pilehead Tabs Standalone v2
 * Plugin URI: https://pilehead.com/
 * Description: Standalone tab system for product pages - Generated by Pilehead Desktop Scraper. Creates independent tabbed content below products.
 * Version: 2.2.0
 * Author: Pilehead
 * Author URI: https://pilehead.com/
 * License: GPL v2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: pilehead-product-tabs
 * Domain Path: /languages
 * Requires at least: 5.0
 * Requires PHP: 7.4
 * WC tested up to: 8.0
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

// Define plugin constants
define('PILEHEAD_TABS_VERSION', '2.2.0');
define('PILEHEAD_TABS_DIR', plugin_dir_path(__FILE__));
define('PILEHEAD_TABS_URL', plugin_dir_url(__FILE__));

/**
 * Remove WooCommerce default product tabs (Description, Additional Info, Reviews)
 * so only Pilehead tabs are shown
 */
add_filter('woocommerce_product_tabs', 'pilehead_remove_default_woo_tabs', 98);

function pilehead_remove_default_woo_tabs($tabs) {
    unset($tabs['description']);
    unset($tabs['additional_information']);
    unset($tabs['reviews']);
    return $tabs;
}

/**
 * Load Pilehead Product Tabs Styles and Scripts on product pages
 */
add_action('wp_enqueue_scripts', 'pilehead_tabs_enqueue_assets', 15);

function pilehead_tabs_enqueue_assets() {
    // Enqueue CSS
    wp_enqueue_style(
        'pilehead-product-tabs',
        PILEHEAD_TABS_URL . 'assets/css/pilehead-product-tabs-style.css',
        array(),
        PILEHEAD_TABS_VERSION,
        'all'
    );
    
    // Enqueue JavaScript (requires jQuery)
    wp_enqueue_script(
        'pilehead-product-tabs-js',
        PILEHEAD_TABS_URL . 'assets/js/pilehead-product-tabs.js',
        array('jquery'),
        PILEHEAD_TABS_VERSION,
        true
    );
}

/**
 * Render Pilehead Product Tabs - Complete Standalone System
 * Using wp_footer because the theme bypasses woocommerce_after_single_product_summary.
 * JavaScript will inject the tabs into the correct DOM position.
 */
add_action('wp_footer', 'pilehead_render_product_tabs', 5);

function pilehead_render_product_tabs() {
    global $product;
    
    if (!$product) {
        return;
    }
    
    $product_id = $product->get_id();
    
    // Define all possible tabs with meta keys
    $tab_definitions = array(
        'overview' => array(
            'title' => __('Overview', 'pilehead-product-tabs'),
            'meta_key' => 'ph_tab_overview_html'
        ),
        'benefits' => array(
            'title' => __('Benefits & Features', 'pilehead-product-tabs'),
            'meta_key' => 'ph_tab_benefits_html'
        ),
        'specifications' => array(
            'title' => __('Specifications', 'pilehead-product-tabs'),
            'meta_key' => 'ph_tab_specifications_html'
        ),
        'applications' => array(
            'title' => __('Applications', 'pilehead-product-tabs'),
            'meta_key' => 'ph_tab_applications_html'
        ),
        'faqs' => array(
            'title' => __('FAQ', 'pilehead-product-tabs'),
            'meta_key' => 'ph_tab_faqs_html'
        ),
        'reviews' => array(
            'title' => __('Reviews', 'pilehead-product-tabs'),
            'meta_key' => 'ph_tab_reviews_html'
        ),
        'delivery' => array(
            'title' => __('Delivery & Shipping', 'pilehead-product-tabs'),
            'meta_key' => 'ph_tab_delivery_html'
        )
    );
    
    // Collect tabs that have content
    $active_tabs = array();
    foreach ($tab_definitions as $key => $tab) {
        $content = get_post_meta($product_id, $tab['meta_key'], true);
        if (!empty($content)) {
            $active_tabs[$key] = array(
                'title' => $tab['title'],
                'content' => $content
            );
        }
    }
    
    // Don't render if no tabs have content
    if (empty($active_tabs)) {
        return;
    }
    
    // Render the complete standalone tab system (hidden, JS will inject into correct position)
    ?>
    <div class="pilehead-product-tabs pilehead-tabs-wrapper" id="pilehead-tabs-<?php echo $product_id; ?>" style="display:none;">
        <div class="pilehead-tabs-nav" role="tablist">
            <?php $first = true; foreach ($active_tabs as $key => $tab): ?>
                <button 
                    class="pilehead-tab-btn<?php echo $first ? ' active' : ''; ?>" 
                    data-tab="<?php echo esc_attr($key); ?>"
                    type="button"
                    role="tab"
                    aria-selected="<?php echo $first ? 'true' : 'false'; ?>"
                    aria-controls="pilehead-panel-<?php echo $product_id; ?>-<?php echo esc_attr($key); ?>">
                    <?php echo esc_html($tab['title']); ?>
                </button>
            <?php $first = false; endforeach; ?>
        </div>
        
        <div class="pilehead-tabs-content">
            <?php $first = true; foreach ($active_tabs as $key => $tab): ?>
                <div 
                    id="pilehead-panel-<?php echo $product_id; ?>-<?php echo esc_attr($key); ?>"
                    class="pilehead-tab-pane<?php echo $first ? ' active' : ''; ?>"
                    data-tab-content="<?php echo esc_attr($key); ?>"
                    role="tabpanel"
                    aria-labelledby="tab-<?php echo esc_attr($key); ?>"
                    style="<?php echo $first ? '' : 'display:none;'; ?>">
                    <?php echo wp_kses_post($tab['content']); ?>
                </div>
            <?php $first = false; endforeach; ?>
        </div>
    </div>
    <?php
}

/**
 * Plugin activation hook
 */
register_activation_hook(__FILE__, 'pilehead_tabs_activation');

function pilehead_tabs_activation() {
    // Flush rewrite rules
    flush_rewrite_rules();
    
    // Add activation notice
    set_transient('pilehead_tabs_activated', true, 5 * MINUTE_IN_SECONDS);
}

/**
 * Plugin deactivation hook
 */
register_deactivation_hook(__FILE__, 'pilehead_tabs_deactivation');

function pilehead_tabs_deactivation() {
    // Flush rewrite rules
    flush_rewrite_rules();
}

/**
 * Display activation message
 */
add_action('admin_notices', 'pilehead_tabs_activation_notice');

function pilehead_tabs_activation_notice() {
    if (get_transient('pilehead_tabs_activated')) {
        ?>
        <div class="notice notice-success is-dismissible">
            <p><?php echo wp_kses_post(__('✅ <strong>Pilehead Tabs Standalone v2</strong> is now active! Custom product tabs will appear below your products.', 'pilehead-product-tabs')); ?></p>
        </div>
        <?php
        delete_transient('pilehead_tabs_activated');
    }

// ─────────────────────────────────────────────────────────────────────────────
// GCS IMAGE CDN — Serve product images straight from Google Cloud Storage
//
// The scraper saves two meta fields on every product:
//   gcs_image_url      → GCS URL for the main product image
//   gcs_gallery_urls   → Pipe-separated GCS URLs for gallery images
//
// These hooks replace the WordPress-hosted image URLs with the GCS URLs so:
//   1. Images load from Google's global CDN (faster worldwide)
//   2. Your WP server doesn't waste bandwidth/CPU serving large images
//   3. WooCommerce still thinks it has its attachment IDs — no side effects
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Server-side: replace main product thumbnail HTML (affects LCP score + SEO).
 */
add_filter('post_thumbnail_html', 'pilehead_gcs_main_image_html', 20, 5);
function pilehead_gcs_main_image_html($html, $post_id, $post_thumbnail_id, $size, $attr) {
    if (!is_product() && !is_singular('product')) return $html;
    $gcs = get_post_meta($post_id, 'gcs_image_url', true);
    if (!$gcs) return $html;
    $url = esc_url($gcs);
    $html = preg_replace('/\ssrc=["\'][^"\']*["\']/',       ' src="'             . $url . '"', $html);
    $html = preg_replace('/\ssrcset=["\'][^"\']*["\']/',    ' srcset=""',                       $html);
    $html = preg_replace('/\sdata-src=["\'][^"\']*["\']/',  ' data-src="'        . $url . '"', $html);
    $html = preg_replace('/\sdata-large_image=["\'][^"\']*["\']/', ' data-large_image="' . $url . '"', $html);
    return $html;
}

/**
 * Server-side: replace each gallery thumbnail HTML.
 * WooCommerce calls this filter once per gallery item with the attachment ID.
 */
add_filter('woocommerce_single_product_image_thumbnail_html', 'pilehead_gcs_gallery_image_html', 20, 2);
function pilehead_gcs_gallery_image_html($html, $attachment_id) {
    global $product;
    if (!$product) return $html;
    $pid      = $product->get_id();
    $main_id  = $product->get_image_id();
    $gal_ids  = $product->get_gallery_image_ids();
    $all_ids  = array_merge([$main_id], $gal_ids);   // main first, then gallery

    $gcs_main = get_post_meta($pid, 'gcs_image_url', true);
    $gcs_raw  = get_post_meta($pid, 'gcs_gallery_urls', true);
    $gcs_gal  = $gcs_raw ? array_filter(explode('|', $gcs_raw)) : [];
    $gcs_all  = array_values(array_filter(array_merge($gcs_main ? [$gcs_main] : [], $gcs_gal)));

    if (empty($gcs_all)) return $html;

    $pos = array_search($attachment_id, $all_ids);
    if ($pos === false || !isset($gcs_all[$pos])) return $html;

    $url  = esc_url($gcs_all[$pos]);
    $html = preg_replace('/\ssrc=["\'][^"\']*["\']/',       ' src="'             . $url . '"', $html);
    $html = preg_replace('/\ssrcset=["\'][^"\']*["\']/',    ' srcset=""',                       $html);
    $html = preg_replace('/\shref=["\'][^"\']*["\']/',      ' href="'            . $url . '"', $html);
    $html = preg_replace('/\sdata-src=["\'][^"\']*["\']/',  ' data-src="'        . $url . '"', $html);
    $html = preg_replace('/\sdata-large_image=["\'][^"\']*["\']/', ' data-large_image="' . $url . '"', $html);
    return $html;
}

/**
 * Output GCS URLs as window.phGCS + a JS fallback that replaces any
 * images that the PHP filters may have missed (e.g. JS-rendered sliders).
 */
add_action('wp_head', 'pilehead_gcs_inline_script', 5);
function pilehead_gcs_inline_script() {
    if (!is_product() && !is_singular('product')) return;
    global $product;
    if (!$product) return;
    $pid      = $product->get_id();
    $main     = get_post_meta($pid, 'gcs_image_url', true);
    $raw_gal  = get_post_meta($pid, 'gcs_gallery_urls', true);
    $gallery  = $raw_gal ? array_values(array_filter(explode('|', $raw_gal))) : [];
    if (!$main && empty($gallery)) return;
    $all = array_values(array_filter(array_merge($main ? [$main] : [], $gallery)));
    ?>
<script>
/* Pilehead GCS image CDN data */
window.phGCS = <?php echo json_encode(['main' => $main ?: '', 'gallery' => $gallery, 'all' => $all], JSON_UNESCAPED_SLASHES); ?>;
(function() {
    function phApplyGCS() {
        var g = window.phGCS;
        if (!g || !g.all || !g.all.length) return;
        /* Main image */
        if (g.main) {
            var mains = document.querySelectorAll(
                '.woocommerce-product-gallery__image img.wp-post-image,' +
                '.woocommerce-product-gallery__wrapper img:first-of-type,' +
                '.product-gallery img:first-of-type'
            );
            if (mains.length) {
                mains[0].src    = g.main;
                mains[0].srcset = '';
                var a0 = mains[0].closest('a');
                if (a0) { a0.href = g.main; a0.setAttribute('data-large_image', g.main); }
            }
        }
        /* Gallery thumbnails */
        var thumbs = document.querySelectorAll(
            '.woocommerce-product-gallery__wrapper .woocommerce-product-gallery__image img,' +
            '.flex-viewport img,' +
            '.woocommerce-product-gallery__image img'
        );
        thumbs.forEach(function(img, i) {
            if (g.all[i]) {
                img.src    = g.all[i];
                img.srcset = '';
                var a = img.closest('a');
                if (a) { a.href = g.all[i]; a.setAttribute('data-large_image', g.all[i]); }
            }
        });
    }
    /* Run immediately + on DOMContentLoaded (for JS-rendered galleries) */
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', phApplyGCS);
    } else {
        phApplyGCS();
    }
    /* Re-run after WC initialises its gallery (flexslider) */
    document.addEventListener('wc-product-gallery-after-init', phApplyGCS);
    window.addEventListener('load', phApplyGCS);
})();
</script>
    <?php
}
}
